language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

os:
  - linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:george-edison55/cmake-3.x'
      - ubuntu-toolchain-r-test
    packages:
      - git
      - cmake-data
      - cmake
      - g++-4.4
      - g++-4.6
      - g++-4.8
      - g++-5
      - g++-6
      - g++-7

env:
  global:
    - GIT_SSL_NO_VERIFY=true
  matrix:
    - GCC=4.4
    - GCC=4.6
    - GCC=4.8
    - GCC=5
    - GCC=6
    - GCC=7

install:
  - export CXX="g++-${GCC}"
  - export CC="gcc-${GCC}"

before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version
  - git --version

script:
  - date
  - mkdir -p /tmp/bosen
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp/bosen .
  - make
  - date

git:
  lfs_skip_smudge: true
  submodules: false

branches:
  only:
    - master

notifications:
  slack:
    on_success: never
    on_failure: never
